--insert into product_order (orderID, email, first_name, last_name, productID) values (1,'george.bluth@reqres.in', 'George', 'Bluth', 34);
--insert into product_order (orderID, email, first_name, last_name, productID) values (2,'emma.wong@reqres.in', 'Emma', 'Wong', 20);
--insert into product_order (orderID, email, first_name, last_name, productID) values (3,'tracey.ramos@reqres.in', 'Tracey', 'Ramos', 25);
--insert into product_order (orderID, email, first_name, last_name, productID) values (4,'tobias.funke@reqres.in', 'Tobias', 'Funk', 38);
--insert into product_order (orderID, email, first_name, last_name, productID) values (5,'rachel.howell@reqres.in', 'Rachel', 'Howell', 41);